### ISSUE TITLE
PB741 (InkPad Color)is identified as wrong device leading to compatability issues in other areas

### ISSUE THREAD

**Issue by TiberiusRegenschein** [zisoft/calibre-pocketbook-device-driver#1]
Hi, I am using a PB741, which is also identified as a PB632 when using this driver. Is there a chance to recognize it as the correct device?

This leads to compatibility issues when e.g. using the [KOReader Sync plugin](https://www.mobileread.com/forums/showthread.php?t=334977&page=4)

Otherwise no issue with the driver so far. Happy to have enhanced functionality with pocketbook on Calibre

**Comment by zisoft** [comment]
Hi and thanks for the feedback!
What compatibility issues are you encountering? I have no idea what the KOReader Sync plugin does.

**Comment by TiberiusRegenschein** [comment]
I am a  big fan of [koreader](https://github.com/koreader/koreader) as my main reader on my pocketbook. Koreader is available for a variety of devices and therefore I can easily start reading on my Linux desktop, continue on my Android and finish on Pocketbook and keep my notes, reading status etc. in sync. The KOReader Sycn plugin simply syncs these annotations, reading progress, with Calibre. For this it needs to know the exact type of Pocketbook connected via USB. With your driver it is told a PB632 is connected while the device connected is a PB741

**Comment by zisoft** [comment]
Can you please go to Calibre --> Preferences --> Advanced --> Miscellaneous --> Debug device detection
and follow the istructions there.
Then post the Device information here.

For my PB632 it is:

USB Vendor ID (in hex): 0xfffe
USB Product ID (in hex): 0x1
USB Revision ID (in hex): 0x101

**Comment by TiberiusRegenschein** [comment]
For my PB741 it is:

USB Vendor ID (in hex): 0xfffe
USB Product ID (in hex): 0x1
USB Revision ID (in hex): 0x101

Which is the same as yours. My assumption is that Pocketbook uses the same USB specification which makes it difficult to identify the device based on those IDs.

KO Highlights needs the device ID to find the right path for the books on the device which is based in the device ID.

Assuming that you do not want your driver to identify itself as Pocketbook and "overwrite" the existing driver the change need to happen on the Sync plugin to accept both.

**Comment by zisoft** [comment]
I do not publish the string "PB632" anywhere in my code...
And my driver is based on the USBMS device driver, nothing special here.

**Comment by Silther** [comment]
[TiberiusRegenschein] has your problem been solved?
Because I too have problems with getting KOReader sync working.

**Comment by CZ75Delta** [comment]
@xIUPITERx 

I looked into it and the issue stems from KoReader Sync reading the device class to detect which device it's connected to. For this driver the device class is currently "POCKETBOOK_IMPROVED" [(as can be seen here)](https://github.com/zisoft/calibre-pocketbook-device-driver/blob/c57ff3c60ed6db38fbf7c4b08db21536cb51208f/device.py#L22)

To add support you can easily add this class into the action.py file located in the KoReader Sync zip file:
![image](https://user-images.githubusercontent.com/33314913/190927767-38d595dc-fc46-4380-918e-9de8afa0f939.png)

I can't guarantee this will work though as it isn't able to find the sidecar files on my device anyway since they're all on the SD card...

**Comment by Silther** [comment]
Thank you, I will try it out at the next opportunity and get back to you.
