### ISSUE TITLE
Book not found on device

### ISSUE THREAD

**Issue by dsferruzza** [zisoft/calibre-pocketbook-device-driver#2]
Hi!

I just tried out your plugin with Calibre (5.40 Win64) and my Vivlio Touch HD Plus (which is basically a Pocketbook 632 for the French market) and I could not get the read statuses to sync.

I started Calibre in debug mode to see what was going on, and it seems your plugin cannot find any of my books because I get this logs for each of them:
```text
DEBUG:   29.4 POCKETBOOK632: Book not found on device: Adam Wiggins: The Twelve-Factor App
DEBUG:   29.4 POCKETBOOK632:  Books\Wiggins, Adam
DEBUG:   29.4 POCKETBOOK632:  The Twelve-Factor App - Adam Wiggins.epub
```
Of course, all my books were pushed on my device by Calibre and Calibre has them marked "on the device" when I plug it in.

Any idea of how to investigate/fix this?

**Comment by zisoft** [comment]
can you please connect your device and look for the path/filename of the book.

From the log output above it is searched in
`books/Wiggins, Adam/The Twelve-Factor App - Adam Wiggins.epub`

Does the file exist at this location?

**Comment by dsferruzza** [comment]
I copied the file's path from Windows File Explorer and got this: `E:\Books\Wiggins, Adam\The Twelve-Factor App - Adam Wiggins.epub`.

I might be missing something because this seems to be correct 🤔 
Maybe the folder name in the database does not includes the `Books/` part?

**Comment by zisoft** [comment]
The problem here is that I need to exactly identify the book in the reader database to get its internal book_id.
For that, I make a database query based on the book title and the author name.
This seems to fail for your constellation.

Would you mind to send me your database file so I can deeply analyse whats going on here?

The database file is located in the readers system directory:
`\system\explorer-3\explorer-3.db`

The system directory is hidden by default, so you need to turn on hidden files to see it.

EDIT:
Ok, I see the problem: My query looks for a folder which matches the author name.
The author name is `Adam Wiggins`, the folder name is `Wiggins, Adams` which does not match.
I need to investigate that further.

**Comment by zisoft** [comment]
Ok, I think I found it.
The path delimiter on the device is a unix based slash /
On Windows devices it is a backslash \

Please check Version 1.0.2 and let me know if this fixes the issue.

**Comment by dsferruzza** [comment]
I was just going to send you my DB but your fix seems to work!
Thanks a lot 🙂
